name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      # with:
      #   submodules: true

    - name: Install Dependencies
      run: |
        npm install
        npm install bs-platform@6.2.1
        npm install webpack webpack-cli

    - name: Build
      run: |
        ./node_modules/.bin/bsb -make-world -clean-world
        ./node_modules/.bin/webpack
    
    - name: Prepare for deployment
      run: |
        mv indexProduction.html index.html
        mkdir public
        cp -r index.html bundleOutput public

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
